name: Pre-commit checks
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'develop'
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: 'Setup latest Python 3.x'
        uses: actions/setup-python@v2
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install -c requirements-dev.txt pre-commit
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - name: 'Setup cache for pre-commit'
        uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
